### ISSUE TITLE
update to fuse-box 3?

### ISSUE THREAD

**Issue by kapilpipaliya** [fuse-box/fuse-box-mobx-ssr-seed#3]
please update to fuse-box 3.

**Comment by nchanged** [comment]
@mattoni could you share the best practices with us? xD

**Comment by mattoni** [comment]
Unfortunately I won't have much time to update this in the next couple weeks. Quite a few things can be improved upon, but I won't have time for awhile. Open to PRs of course, and will try to get to this sometime in March.
